name: T-Cloud Ephemeral Engine
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Bare-Metal Kernel
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io tmux
        
    - name: Inject Cloudflare Tunnel (Secure Routing)
      run: |
        curl -L --output cloudflared.deb https://github.com
        sudo dpkg -i cloudflared.deb
        
        tmux new-session -d -s tunnel 'cloudflared tunnel run --token ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}'
        
    - name: Keep-Alive Micro-Kernel Engine
      run: |
        echo "السيرفر السحابي الخارق يعمل الآن بأقصى طاقة..."
        sleep 21600
        
